version: 2.1

jobs:
  compile:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - run: node --version
      - run: npm run build
  test:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - run: npm test

workflows:
  build_and_test:
    jobs:
      - compile:
      - test:
        requires:
          - test
