version: 2.1

commands:
  install_deps:
    description: "Install project dependencies"
    steps:
      - run: npm install
      - run: cd packages/admin && npm install

jobs:
  lint_and_format_check:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - install_deps
      - run: npm run lint
      - run: npm run format-check
  compile:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - install_deps
      - run: rm -rf packages/admin/lib
      - run: npm run build
  test:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - install_deps
      - run: npm test

workflows:
  build_and_test:
    jobs:
      - lint_and_format_check
      - compile
      - test: # TODO: Make sure to compile tests as well (with noEmit)
          requires:
            - compile
            - lint_and_format_check
